#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Gabriel Henrique Lopes Gomes Alves Nunes

"""Rebuild the fixtures that exercise check-contrast.py --design-system.

The vocabulary is read from DESIGN_SYSTEM_PAIRS rather than repeated, so
a pair added there is covered here on the next run and cannot be silently
left unexercised.

Usage: python3 scripts/fixtures/regenerate.py
"""

import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CHECKER = HERE.parent / "check-contrast.py"

HEADER = """/* SPDX-License-Identifier: AGPL-3.0-or-later */
/* SPDX-FileCopyrightText: 2026 Gabriel Henrique Lopes Gomes Alves Nunes */

/*
 * {what}
 *
 * The palette that mode audits is brand material and is not in this
 * repository, so nothing here could otherwise show that the mode works.
 * This file carries the same four-block shape and the same token
 * vocabulary, in black and white so every pair sits at 21:1 and any
 * failure is the checker's rather than a palette's.
 *
 * Generated by scripts/fixtures/regenerate.py. Regenerate after changing
 * DESIGN_SYSTEM_PAIRS, or the mode gains a pair this cannot exercise.
 */
"""


def load_checker():
    spec = importlib.util.spec_from_file_location("check_contrast", CHECKER)
    module = importlib.util.module_from_spec(spec)
    sys.dont_write_bytecode = True
    spec.loader.exec_module(module)
    return module


BLOCKS = [
    (":root", "#000000", "#ffffff"),
    (".theme-dark", "#ffffff", "#000000"),
    (".contrast-high", "#000000", "#ffffff"),
    (".theme-dark.contrast-high", "#ffffff", "#000000"),
]


def document(foregrounds, backgrounds, what, nudge_in=None, nudge=None):
    """One fixture. `nudge_in` names the single block to spoil, if any.

    Spoiling exactly one block is what makes the fixture prove the layering
    rather than only the arithmetic: every block here sets every token, so
    a checker that ignored that block would fall back to a value that
    passes, and the failure it was supposed to see would disappear.
    """

    def block(selector, fg_colour, bg_colour):
        lines = [f"{selector} {{"]
        for token in foregrounds:
            value = nudge if selector == nudge_in and token == "--fg-muted" else fg_colour
            lines.append(f"  {token}: {value};")
        for token in backgrounds:
            lines.append(f"  {token}: {bg_colour};")
        return "\n".join(lines + ["}"])

    return (
        "\n\n".join(
            [HEADER.format(what=what).rstrip()]
            + [block(*spec) for spec in BLOCKS]
        )
        + "\n"
    )


def main():
    checker = load_checker()
    foregrounds = sorted({pair[0] for pair in checker.DESIGN_SYSTEM_PAIRS})
    backgrounds = sorted({pair[1] for pair in checker.DESIGN_SYSTEM_PAIRS})

    written = 0
    (HERE / "design-system-conforming.css").write_text(
        document(
            foregrounds,
            backgrounds,
            "A palette that meets every threshold, for check-contrast.py --design-system.",
        )
    )
    written += 1

    # One fixture per mode, each spoiling --fg-muted in that mode's block
    # alone. The two high-contrast values clear 4.5:1 and miss 7:1, so they
    # also prove the threshold is chosen by mode rather than fixed.
    for selector, grey, mode, why in [
        (":root", "#a0a0a0", "light", "2.61:1 on white, under the 4.5:1 for body text"),
        (".theme-dark", "#4a4a4a", "dark", "2.37:1 on black, under the 4.5:1 for body text"),
        (".contrast-high", "#6a6a6a", "high-light", "5.41:1, over 4.5:1 but under the 7:1 this mode owes"),
        (".theme-dark.contrast-high", "#8a8a8a", "high-dark", "6.08:1, over 4.5:1 but under the 7:1 this mode owes"),
    ]:
        (HERE / f"design-system-failing-{mode}.css").write_text(
            document(
                foregrounds,
                backgrounds,
                f"The conforming fixture with --fg-muted spoiled in {selector} only:\n"
                f" * {why}. Every other mode still passes, so a checker that\n"
                " * ignored that block would report this palette as clean.",
                selector,
                grey,
            )
        )
        written += 1

    print(
        f"regenerated {written} fixtures covering {len(foregrounds)} foreground "
        f"and {len(backgrounds)} background tokens"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
