// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Gabriel Henrique Lopes Gomes Alves Nunes
//! Access map persistence and Postfix map generation.
//!
//! Maintains the lists of blocked recipient addresses and per-pair
//! sender blocks in a JSON file that survives container restarts
//! (stored on the mounted `chatmail-data` volume).

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};
use tracing::{info, warn};

use crate::config::Config;

/// Persistent access map state.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AccessMaps {
    /// Recipient addresses for which inbound mail is rejected
    /// (suspended or deleted accounts).
    pub blocked_recipients: BTreeSet<String>,
    /// Per-pair sender blocks: `sender_addr to set of recipient_addrs`.
    /// Mail from `sender` to any address in the set is rejected.
    pub sender_blocks: BTreeMap<String, BTreeSet<String>>,
}

impl AccessMaps {
    /// Load from the persistence file, or initialise empty maps if the
    /// file does not exist or is malformed.
    pub fn load_or_init(path: &str) -> Self {
        let p = Path::new(path);
        if p.exists() {
            match fs::read_to_string(p) {
                Ok(json) => match serde_json::from_str(&json) {
                    Ok(maps) => {
                        info!(path = %path, "loaded access maps from disk");
                        return maps;
                    }
                    Err(e) => warn!(path = %path, error = %e, "malformed access maps file; reinitialising"),
                },
                Err(e) => warn!(path = %path, error = %e, "failed to read access maps file; reinitialising"),
            }
        }
        Self::default()
    }

    /// Persist the current state to the JSON file.
    pub fn save(&self, path: &str) -> std::io::Result<()> {
        let p = Path::new(path);
        if let Some(parent) = p.parent() {
            fs::create_dir_all(parent)?;
        }
        let json = serde_json::to_string_pretty(self)
            .map_err(std::io::Error::other)?;
        fs::write(p, json)?;
        info!(path = %path, "access maps persisted to disk");
        Ok(())
    }

    /// Write the Postfix `check_recipient_access` and `check_sender_access`
    /// map files and regenerate the hash `.db` files via `postmap`.
    pub fn write_postfix_maps(&self, config: &Config) {
        if let Err(e) = self.write_recipient_map(&config.recipient_access_path) {
            warn!(error = %e, "failed to write recipient access map");
        } else {
            let _ = std::process::Command::new("postmap")
                .arg(&config.recipient_access_path)
                .status();
        }
        if let Err(e) = self.write_sender_map(&config.sender_access_path) {
            warn!(error = %e, "failed to write sender access map");
        } else {
            let _ = std::process::Command::new("postmap")
                .arg(&config.sender_access_path)
                .status();
        }
    }

    /// Generate the `check_recipient_access` file.
    ///
    /// Format: one `address REJECT` line per blocked recipient.
    fn write_recipient_map(&self, path: &str) -> std::io::Result<()> {
        let mut f = fs::File::create(path)?;
        writeln!(f, "# Generated by noombat-chatmail-admin. Do not edit.")?;
        for addr in &self.blocked_recipients {
            writeln!(f, "{addr} REJECT account suspended or deleted")?;
        }
        info!(path = %path, entries = self.blocked_recipients.len(), "wrote recipient access map");
        Ok(())
    }

    /// Generate the `check_sender_access` file.
    ///
    /// Writes one `sender REJECT` line per sender that has at least one
    /// per-pair block, regardless of which recipients are blocked. This
    /// is a best-effort enforcement:
    /// Postfix evaluates `check_sender_access` before recipient
    /// information is available, so true per-pair granularity is not
    /// achievable with flat access maps alone (it would require a milter
    /// or policy service). Application-level per-pair enforcement in the
    /// `noombat-chat` proxy remains the primary mechanism; this map
    /// provides a transport-level backstop for senders who have exported
    /// credentials to an external client.
    fn write_sender_map(&self, path: &str) -> std::io::Result<()> {
        let mut f = fs::File::create(path)?;
        writeln!(f, "# Generated by noombat-chatmail-admin. Do not edit.")?;
        let mut count = 0usize;
        for (sender, recipients) in &self.sender_blocks {
            if !recipients.is_empty() {
                writeln!(f, "{sender} REJECT blocked by moderation")?;
                count += 1;
            }
        }
        info!(path = %path, entries = count, "wrote sender access map");
        Ok(())
    }
}
