// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Gabriel Henrique Lopes Gomes Alves Nunes
//! Chatmail closed-federation allowlist synchronisation.
//!
//! Polls the published allowlist JSON document at a configurable URL
//! (default: `https://noombat.org/chatmail-allowlist.json`) and
//! regenerates the Postfix `transport_maps` file on change.

use std::collections::BTreeSet;
use std::fs;
use std::io::Write;
use std::sync::Arc;
use std::time::Duration;

use serde::Deserialize;
use tracing::{info, warn};

use crate::AppState;

/// Shape of the published allowlist JSON document.
///
/// Expected at `https://noombat.org/chatmail-allowlist.json`:
///
/// ```json
/// {
///   "domains": [
///     "chat.noombat.social",
///     "chat.careers.acme.com"
///   ]
/// }
/// ```
#[derive(Debug, Deserialize)]
struct AllowlistDocument {
    domains: Vec<String>,
}

/// Start the allowlist polling loop in a background thread.
///
/// The loop runs indefinitely, polling the allowlist URL at the
/// configured interval. On each successful fetch, if the domain set
/// has changed, the `transport_maps` file is regenerated and Postfix
/// is reloaded.
pub fn start_polling(state: Arc<AppState>) {
    let url = state.config.allowlist_url.clone();
    let interval = Duration::from_secs(state.config.allowlist_poll_interval_secs);
    let transport_maps_path = state.config.transport_maps_path.clone();

    if url.is_empty() {
        info!("allowlist URL not configured; synchronisation disabled");
        return;
    }

    std::thread::spawn(move || {
        info!(
            url = %url,
            interval_secs = interval.as_secs(),
            "allowlist polling started"
        );

        let agent: ureq::Agent = ureq::Agent::config_builder()
            .timeout_global(Some(Duration::from_secs(30)))
            .build()
            .into();
        let mut last_domains: BTreeSet<String> = BTreeSet::new();

        loop {
            match fetch_allowlist(&agent, &url) {
                Ok(domains) => {
                    if domains != last_domains {
                        info!(
                            count = domains.len(),
                            "allowlist changed; regenerating transport_maps"
                        );
                        if let Err(e) = write_transport_maps(&transport_maps_path, &domains) {
                            warn!(error = %e, "failed to write transport_maps");
                        } else {
                            // Trigger postmap and postfix reload.
                            let _ = std::process::Command::new("postmap")
                                .arg(&transport_maps_path)
                                .status();
                            let _ = std::process::Command::new("postfix").arg("reload").status();
                            info!("transport_maps regenerated and postfix reloaded");
                        }
                        last_domains = domains;
                    }
                }
                Err(e) => {
                    warn!(url = %url, error = %e, "allowlist fetch failed");
                }
            }

            std::thread::sleep(interval);
        }
    });
}

/// Fetch the allowlist JSON document from the given URL.
///
/// Uses a blocking HTTP GET via `ureq`. The caller provides
/// a pre-configured [`ureq::Agent`] with the desired timeout.
fn fetch_allowlist(
    agent: &ureq::Agent,
    url: &str,
) -> Result<BTreeSet<String>, Box<dyn std::error::Error>> {
    let body: String = agent.get(url).call()?.body_mut().read_to_string()?;
    let doc: AllowlistDocument = serde_json::from_str(&body)?;
    Ok(doc.domains.into_iter().collect())
}

/// Write the Postfix `transport_maps` file.
///
/// Each allowlisted domain gets a line `domain smtp:[domain]`,
/// directing Postfix to deliver to that domain via SMTP. Domains
/// not in the map receive no transport entry, causing Postfix to
/// reject delivery attempts (the default transport is not configured
/// for external delivery).
fn write_transport_maps(path: &str, domains: &BTreeSet<String>) -> std::io::Result<()> {
    let mut f = fs::File::create(path)?;
    writeln!(
        f,
        "# Generated by noombat-chatmail-admin allowlist sync. Do not edit."
    )?;
    for domain in domains {
        writeln!(f, "{domain} smtp:[{domain}]")?;
    }
    info!(path = %path, entries = domains.len(), "wrote transport_maps");
    Ok(())
}
